config/routes.rb
Rails.application.routes.draw do
  resources :pitis do
    collection do
      get 'default'
    end
  end

  resources :listings
  root 'welcome#index'

  get 'parse' => 'welcome#parse'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :pitis

  validates :mls, uniqueness: { message: "This listing has already been added" }
end

app/models/mls_parser.rb
module MlsParser
  require 'open-uri'

  @base_url = 'http://maxebrdi.paragonrels.com/publink/'

  def self.parse(url)
    uri = URI(url)
    gui = CGI::parse(uri.query)['GUID'].first
    left_url = nil;

    doc = Nokogiri::HTML(open(url))
    doc.xpath("//frame").each do |frame|
        if frame['name'] == 'left'
            left_url = frame['src']
        end
    end

    listings = []
    doc = Nokogiri::HTML(open("#{@base_url}#{left_url}"))
    doc.xpath("//td/a").each do |link|
        target = link["onclick"].split("'")[1]

        mls = {
          gui: gui,
          target: target,
          mls: link.text
        }
        mls.merge!(self.parse_house(self.link(mls)));
        listings << mls
    end

    return listings
  end

  def self.parse_house(url)
    doc = Nokogiri::HTML(open(url)).xpath("//div")
    # doc.each_with_index do |v, i|
    #   puts "#{i}: #{v.text}"
    # end


    data = {
      address: "#{doc[98].text}, #{doc[99].text}, #{doc[100].text}",
      price: doc[102].text.gsub(/[\D]/, '').to_i,
      sqft: doc[134].text.to_i
    }
    return data
  end

  def self.link(info)
    return "#{@base_url}Report.aspx?outputtype=HTML&GUID=#{info[:gui]}&ListingID=#{info[:target]}&Report=Yes&view=29&layout_id=1910"
  end
end

app/models/piti.rb
class Piti < ActiveRecord::Base
  belongs_to :listing

  INTEREST = 4.57
  MATURITY = 360
  INSURANCE = 800
  TAX = 1.25

  before_create do
    self.interest  = INTEREST if self.interest.blank?
    self.maturity  = MATURITY if self.maturity.blank?
    self.insurance = INSURANCE if self.insurance.blank?
    self.tax = TAX if self.tax.blank?
  end

  def self.build
    piti = self.new
    piti.interest  = INTEREST
    piti.maturity  = MATURITY
    piti.insurance = INSURANCE
    piti.tax = TAX

    return piti
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html { render index: @listings}
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:mls, :gui, :target, :address, :price, :sqft)
    end
end

app/controllers/pitis_controller.rb
class PitisController < ApplicationController
  before_action :set_piti, only: [:show, :edit, :update, :destroy]

  # GET /pitis
  # GET /pitis.json
  def index
    @pitis = Piti.all

    respond_to do |format|
      format.html { render index: @pitis }
      format.json { render json: @pitis }
    end
  end

  # GET /pitis/1
  # GET /pitis/1.json
  def show
  end

  # GET /pitis/new
  def new
    @piti = Piti.new
  end

  # GET /pitis/1/edit
  def edit
  end

  # POST /pitis
  # POST /pitis.json
  def create
    @piti = Piti.new(piti_params)

    respond_to do |format|
      if @piti.save
        format.html { redirect_to @piti, notice: 'Piti was successfully created.' }
        format.json { render :show, status: :created, location: @piti }
      else
        format.html { render :new }
        format.json { render json: @piti.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitis/1
  # PATCH/PUT /pitis/1.json
  def update
    respond_to do |format|
      if @piti.update(piti_params)
        format.html { redirect_to @piti, notice: 'Piti was successfully updated.' }
        format.json { render :show, status: :ok, location: @piti }
      else
        format.html { render :edit }
        format.json { render json: @piti.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitis/1
  # DELETE /pitis/1.json
  def destroy
    @piti.destroy
    respond_to do |format|
      format.html { redirect_to pitis_url, notice: 'Piti was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /pitis/default
  # GET /pitis/default.json
  def default
    data = {
      default: Piti.build,
      tax: Piti::TAX,
      insurance: Piti::INSURANCE,
      maturity: Piti::MATURITY,
      interest: Piti::INTEREST
    }


    respond_to do |format|
      format.html { redirect_to pitis_url, notice: 'Piti was successfully destroyed.' }
      format.json { render json: data, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piti
      @piti = Piti.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piti_params
      params.require(:piti).permit(:listing_id, :price, :down, :interest, :maturity, :tax, :insurance)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render "index"
  end

  def parse
    @listings = MlsParser::parse(params["url"])
    render "parse"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pitis_helper.rb
module PitisHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- <link rel="icon" href="../../favicon.ico"> -->

  <title>MLS Parser</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- AngularJS 1.4.5 -->
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>

  <%= javascript_include_tag 'application' %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <!-- animation library -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-animate.min.js"></script>

  <%= csrf_meta_tags %>
</head>

<body role="document" ng-app="ngMls">

  <!-- Fixed navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "MLS Helper", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Listings", listings_path %></li>
          <li><a href="#about">About</a></li>
          <!--
          <li><a href="#contact">Contact</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          -->
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container theme-showcase" role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <h1>The Parser</h1>
      <p>This tool is design to make shopping a little easier.</p>
    </div>

    <%= yield %>


  </div> <!-- /container -->
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mls %><br>
    <%= f.text_field :mls %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :sqft %><br>
    <%= f.number_field :sqft %>
  </div>
  <div class="field">
    <%= f.label :gui %><br>
    <%= f.text_field :gui %>
  </div>
  <div class="field">
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Mls</th>
      <th>Address</th>
      <th>Price</th>
      <th>Sqft</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.mls %></td>
        <td><%= listing.address %></td>
        <td><%= listing.price %></td>
        <td><%= listing.sqft %></td>
        <td><%= link_to 'Link', MlsParser.link({ mls: listing.mls, gui: listing.gui, target: listing.target }) %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<div class="container-fluid" ng-controller="ngPitiCtrl">
  <% @listings.each do |listing| %>

  <div class="panel panel-primary">
    <div class="panel-body">
      <div class="col-md-1">
        <button type="button" ng-click="piti_<%= listing.id %> = !piti_<%= listing.id %>" class="btn btn-link btn-xs">
          <span ng-class="(!piti_<%= listing.id %>) ? 'glyphicon glyphicon-menu-right' : 'glyphicon glyphicon-menu-down'"></span>
        </button>
      </div>
      <div class="col-md-2"><%= listing.mls %></div>
      <div class="col-md-3"><%= (listing.address || '').titleize %></div>
      <div class="col-md-1"><%= listing.sqft %> ft.</div>
      <div class="col-md-3"><%= number_to_currency(listing.price) %></div>
      <div class="col-md-2">
        <%= link_to(MlsParser.link({ mls: listing.mls, gui: listing.gui, target: listing.target })) do %>
          <span class="glyphicon glyphicon-link"></span>
        <% end %>
        <%= link_to(listing) do %>
          <span class="glyphicon glyphicon-file"></span>
        <% end %>
        <%= link_to(edit_listing_path(listing)) do %>
          <span class="glyphicon glyphicon-edit"></span>
        <% end %>
        <%= link_to(listing, method: :delete, data: { confirm: 'Are you sure?' }) do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </div>
    </div>

    <!-- Table -->
    <table class="table table-stripped" ng-show="piti_<%= listing.id %>">
      <tr>
        <th>
          <button type="button" ng-click="addPiti(<%= listing.id %>)" class="btn btn-link btn-xs">
            <span class="glyphicon glyphicon-plus"></span>
          </button>
        </th>
        <th>Price</th>
        <th>Down</th>
        <th>Interest</th>
        <th>Maturity</th>
        <th>Insurance</th>
        <th>Tax</th>
        <th>Final Payment</th>
        <th></th>
      </tr>
      <tr ng-repeat="piti in pitis[<%= listing.id %>]" ng-class="{'bg-success': piti.saved}">
        <td>
          <div ng-show="piti.saved" class="saved fadein fadeout">
            <i class="fa fa-check"></i>
          </div>
        </td>
        <td class="col-md-2">
          <div class="input-group input-group-sm">
            <span class="input-group-addon" id="sizing-addon1">$</span>
            <input type="text" class="form-control" placeholder="Price" ng-model="piti.price" size="3" />
          </div>
        </td>
        <td class="col-md-2">
          <div class="input-group input-group-sm">
            <span class="input-group-addon" id="sizing-addon1">$</span>
            <input type="text" class="form-control" placeholder="Down Payment" ng-model="piti.down" size="30" />
          </div>
        </td>
        <td class="col-md-2">
          <div class="input-group input-group-sm">
            <input type="text" class="form-control" placeholder="Interests" ng-model="piti.interest" size="7" />
            <span class="input-group-addon" >%</span>
          </div>
        </td>
        <td class="col-md-1">{{ piti.maturity || maturity }}</td>
        <td class="col-md-1">{{ piti.insurance || insurance }}</td>
        <td class="col-md-1">{{ piti.tax || tax }}%</td>
        <td class="col-md-2">${{ calculatedPayment(piti) | number: 2}}</td>
        <td class="col-md-1">
          <button ng-click="update(piti)" class="btn btn-link">
            <span class="glyphicon glyphicon-floppy-disk"></sm>
          </button>
        </td>
      </tr>
    </table>
  </div>
  <% end %>
</div>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mls:</strong>
  <%= @listing.mls %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Sqft:</strong>
  <%= @listing.sqft %>
</p>

<p>
  <strong>Gui:</strong>
  <%= @listing.gui %>
</p>

<p>
  <strong>Target:</strong>
  <%= @listing.target %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pitis/_calc_form.html.erb
<%= form_for(@piti, html: { class: 'form-inline'}) do |f| %>
  <% if @piti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piti.errors.count, "error") %> prohibited this piti from being saved:</h2>

      <ul>
      <% @piti.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :listing_id %><br>
    <%= f.text_field :listing_id %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="form-group">
    <%= f.label :down %><br>
    <%= f.number_field :down %>
  </div>
  <div class="form-group">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="form-group">
    <%= f.label :maturity %><br>
    <%= f.text_field :maturity %>
  </div>
  <div class="form-group">
    <%= f.label :tax %><br>
    <%= f.text_field :tax %>
  </div>
  <div class="form-group">
    <%= f.label :insurance %><br>
    <%= f.number_field :insurance %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitis/_form.html.erb
<%= form_for(@piti) do |f| %>
  <% if @piti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piti.errors.count, "error") %> prohibited this piti from being saved:</h2>

      <ul>
      <% @piti.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :listing_id %><br>
    <%= f.text_field :listing_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :down %><br>
    <%= f.number_field :down %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :maturity %><br>
    <%= f.text_field :maturity %>
  </div>
  <div class="field">
    <%= f.label :tax %><br>
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :insurance %><br>
    <%= f.number_field :insurance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitis/edit.html.erb
<h1>Editing Piti</h1>

<%= render 'form' %>

<%= link_to 'Show', @piti %> |
<%= link_to 'Back', pitis_path %>

app/views/pitis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pitis</h1>

<table>
  <thead>
    <tr>
      <th>Listing</th>
      <th>Price</th>
      <th>Down</th>
      <th>Interest</th>
      <th>Maturity</th>
      <th>Tax</th>
      <th>Insurance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitis.each do |piti| %>
      <tr>
        <td><%= piti.listing %></td>
        <td><%= piti.price %></td>
        <td><%= piti.down %></td>
        <td><%= piti.interest %></td>
        <td><%= piti.maturity %></td>
        <td><%= piti.tax %></td>
        <td><%= piti.insurance %></td>
        <td><%= link_to 'Show', piti %></td>
        <td><%= link_to 'Edit', edit_piti_path(piti) %></td>
        <td><%= link_to 'Destroy', piti, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Piti', new_piti_path %>

app/views/pitis/new.html.erb
<h1>New Piti</h1>

<%= render 'form' %>

<%= link_to 'Back', pitis_path %>

app/views/pitis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listing:</strong>
  <%= @piti.listing %>
</p>

<p>
  <strong>Price:</strong>
  <%= @piti.price %>
</p>

<p>
  <strong>Down:</strong>
  <%= @piti.down %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @piti.interest %>
</p>

<p>
  <strong>Maturity:</strong>
  <%= @piti.maturity %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @piti.tax %>
</p>

<p>
  <strong>Insurance:</strong>
  <%= @piti.insurance %>
</p>

<%= render 'calc_form' %>

<%= link_to 'Edit', edit_piti_path(@piti) %> |
<%= link_to 'Back', pitis_path %>

app/views/welcome/index.html.erb
<h2>
  Welcome!
</h2>

<h5>
  Please enter the url provided by the realtor:
</h5>

<div>
  <%= form_tag("/parse", method: "get", class: "form-inline") do %>
    <div class="form-group">
      <input type="text" name="url" class="form-control" />
    </div>
    <%= submit_tag("Submit", class: "btn btn-default") %>
  <% end %>
</div>

app/views/welcome/parse.html.erb
<h5>
  Please enter the url provided by the realtor:
</h5>

<div>
  <%= form_tag("/parse", method: "get", class: "form-inline") do %>
    <div class="form-group">
      <input type="text" name="url" class="form-control" />
    </div>
    <%= submit_tag("Submit", class: "btn btn-default") %>
  <% end %>
</div>

<hr />

<h3>Your results:</h3>

<div class="container">
  <div class="list-group">
    <div class="row list-group-item active">
      <div class="col-md-2"><strong>MLS Link</strong></div>
      <div class="col-md-5"><strong>Address</strong></div>
      <div class="col-md-2"><strong>Square Footage</strong></div>
      <div class="col-md-2"><strong>Price</strong></div>
      <div class="col-md-1"></div>
    </div>
    <% @listings.each do |mls| %>
    <div class="row list-group-item">
      <%= form_tag("/listings", method: "post") do %>
        <%= hidden_field_tag('listing[mls]', mls[:mls]) %>
        <%= hidden_field_tag('listing[gui]', mls[:gui]) %>
        <%= hidden_field_tag('listing[target]', mls[:target]) %>
        <%= hidden_field_tag('listing[address]', mls[:address]) %>
        <%= hidden_field_tag('listing[price]', mls[:price]) %>
        <%= hidden_field_tag('listing[sqft]', mls[:sqft]) %>
        <div class="col-md-2"><%= link_to mls[:mls], MlsParser.link(mls) %></div>
        <div class="col-md-5"><%= mls[:address] %></div>
        <div class="col-md-2"><%= mls[:sqft] %> ft.</div>
        <div class="col-md-2">$<%= number_to_currency(mls[:price]) %></div>
        <div class="col-md-1"><%= submit_tag("add", class: 'btn btn-primary btn-xs') %></div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>